version: '3.8'

services:
  jekyll:
    build: .
    ports:
      - "4000:4000"
    volumes:
      # Mount the source code for live reload
      - .:/srv/jekyll
      # Exclude vendor directory to avoid conflicts
      - /srv/jekyll/vendor
    environment:
      - JEKYLL_ENV=development
      - JEKYLL_SERVE_HOST=0.0.0.0
    command: jekyll serve --livereload --host 0.0.0.0
    restart: unless-stopped 